export const SUCCESS = "success"
export const FAILURE = "failure"
export const ERROR = "error"
export const CHANGE = "change"
export const IDK = "idk"
export const REQUEUE = "requeue"
export const REMOVE = "remove"
export const RESET = "reset"